dchest:
  access: 0
  removelevel: false
  clean: 10800
  warning: 900
  critical: 60
  random:
    chance: 100
    itemsecond: 3
    countdown: 30
  enabled: true

hchest:
  access: 5
  removelevel: false
  keepondeath: true
  enabled: true

mchest:
  access: 10
  removelevel: false
  lockout: 300
  enabled: true

rchest:
  access: 5
  removelevel: true
  lockout: 300
  timer: 15
  enabled: true

schest:
  access: 2
  removelevel: true
  enabled: true

vchest:
  access: 5
  removelevel: true
  upgradelevel: 25
  enabled: true

xchest:
  access: 10
  removelevel: false
  lockout: 300
  enabled: true