name: ${project.name}
version: ${project.version}
description: ${project.description}

author: Ullarah

main: ${project.groupId}.${project.artifactId}.LotteryInit

softdepend: [Vault]

commands:
  lottery:
    description: View lottery statistics
    usage: |
      <command> : Shows Help.
      <command> exclude / e / x <player< : Excludes player from lottery.
      <command> force / f : Forces lottery win.
      <command> history / h : Shows winning history.
      <command> include / i <player> : Includes player to lottery.
      <command> reset / r : Resets lottery.
      <command> version / v : Shows current plugin version.

permissions:
  ulottery.admin:
    description: Allows the use of exclude/include options.