name: ${project.name}
version: ${project.version}
description: ${project.description}

author: Ullarah

main: ${project.groupId}.${project.artifactId}.LotteryInit

softdepend: [Vault]

commands:
  lottery:
    description: View lottery statistics
