name: ${project.name}
version: ${project.version}
description: ${project.description}

author: Ullarah

softdepend: [WorldEdit, WorldGuard]

main: ${project.groupId}.${project.artifactId}.MagicInit

permissions:
  magic.bypass:
    description: Bypass WorldGuard region access.