name: ${project.name}
version: ${project.version}
description: ${project.description}

author: Ullarah

softdepend: [WorldEdit, WorldGuard]

main: ${project.groupId}.${project.artifactId}.MagicInit

commands:
  n-hoe:
    description: Hoe Crafting Command
    usage: |
      <command> : Gives a normal magical hoe.
  s-hoe:
    description: Hoe Crafting Command
    usage: |
      <command> : Gives a super magical hoe.
  u-hoe:
    description: Hoe Crafting Command
    usage: |
      <command> : Gives a uber magical hoe.

permissions:
  umagic.danger:
    description: Allows usage of dangerous conversions
  umagic.usage:
    description: Allows usage of the Magic Hoe
  umagic.bypass:
    description: Bypass WorldGuard region access
  umagic.gethoe:
    description: Obtain a Magic Hoe without crafting